### ISSUE TITLE
安装feed组件，resolve的时候出错

### ISSUE THREAD

**Issue by kuse2001** [slimkit/plus-component-h5#105]
![image](https://user-images.githubusercontent.com/12782761/30511292-403a213c-9b08-11e7-8966-8825fd51416e.png)

**Comment by kuse2001** [comment]
搞错坛子了，帮我转移到feed吧

**Comment by boxshadow** [comment]
@kuse2001 最新的动态扩展包还未打包，可以先使用本地开发模式来操作
