### ISSUE TITLE
【首页--动态】发布动态的时间显示不对

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-component-h5#133]
## 配图
H5
![image](https://user-images.githubusercontent.com/30249193/30894473-88afe318-a376-11e7-975a-32e2064bece3.png)

app
![image](https://user-images.githubusercontent.com/30249193/30894479-9569efd6-a376-11e7-909f-f8acde2ea13e.png)

**Comment by boxshadow** [comment]
由客户端时间决定时间的解析方式，不可控
