### ISSUE TITLE
yarn dist打包错误

### ISSUE THREAD

**Issue by sucof** [slimkit/plus-component-h5#140]
使用yarn dist进行打包，会产生error Command failed with exit code 2错误

**Comment by boxshadow** [comment]
@sucof 要看错误开始的地方的提示，最后一句是看不出什么名堂的

**Comment by sucof** [comment]
出错的地方一般是如下所示：
`ERROR in ./~/css-loader?{"minimize":true,"sourceMap":false,"localIdentName":"[hash:base64]_0","modules":true,"importLoaders":true}!./~/vue-loader/lib/style-compiler?{"id":"data-v-3459da6d","scoped":false,"hasInlineConfig":false}!./~/sass-loader/lib/loader.js?{"sourceMap":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/views/SearchPop/SearchPop.vue
    Module build failed: Error: Missing binding /home/vagrant/thinksns-plus/resources/repositorie/sources/zhiyicx-plus-component-h5/node_modules/node-sass/vendor`，说是缺少vendor文件，但是已通过npm install 进行安装相关组件，确实没用相关文件。然后利用yarn dist命令进行打包
yarn 版本：v1.1.0
很奇怪，其它 yarn dev等没有错误

**Comment by JsonLeex** [comment]
报错是marked-plus-image这个包引起的 @medz，大佬处理一下

**Comment by medz** [comment]
已修复。

**Comment by JsonLeex** [comment]
问题解决了，建议你删除 `yarn.lock` 或者 `package-lock.json` , 然后从新安装依赖，再打包。
