### ISSUE TITLE
【发现--资讯】文章被置顶后在该栏目下没有置顶标识

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-component-h5#163]
## 配图
![image](https://user-images.githubusercontent.com/30249193/32042798-63b8e8b4-ba6b-11e7-96a6-dd34b78330dd.png)
app端
![image](https://user-images.githubusercontent.com/30249193/32042810-7335fa98-ba6b-11e7-95d0-4ccd0545cea7.png)
## 用例
![image](https://user-images.githubusercontent.com/30249193/32042840-8e006606-ba6b-11e7-9a19-bdf878c9795c.png)

**Comment by huhaophp** [comment]
已添加
