### ISSUE TITLE
【我--收藏】在动态列表页收藏动态之后进入我--收藏，动态列表上未显示收藏的动态

### ISSUE THREAD

**Issue by maanrry** [slimkit/plus-component-h5#185]
##  描述
在动态列表页收藏动态之后进入我--收藏，动态列表上未显示收藏的动态
## 配图
![image](https://user-images.githubusercontent.com/30249193/32051763-7c3f01da-ba88-11e7-9f06-ea702ef79f75.png)
动态列表
![image](https://user-images.githubusercontent.com/30249193/32051787-9262deb4-ba88-11e7-8261-8f76c7e33b47.png)

**Comment by huhaophp** [comment]
新版本已修改
